deployment:
  name: tetris
  replicaCount: 5
image:
  repository: opqtech/tetris
  tag: v1.0.0
  containerPort: 3000
service:
  type: ClusterIP
  clusterIPPort: 3000
resource:
  cpu:
    requests: 0.2
    limit: 0.5
  memory:
    requests: 500Mi
    limit: 800Mi
environment:
  env: prod
namespace: prod
